module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      print: { raw: "print" },
    },
    fontFamily: {
      sans: [
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Roboto",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ["Georgia", "Cambria", '"Times New Roman"', "Times", "serif"],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        '"Liberation Mono"',
        '"Courier New"',
        "monospace",
      ],
    },
    colors: {
      orange: "#FFA500",
      light_orange: "#FFF7E8",
      mid_orange: "#FFCD71",
      dark_orange: "#734A00",
      dark_grey: "#454545",
      dark_red: "#B01212",
      mid_gray: "#7D7D7D",
      off_black: "#131313",
      black: "#000",
      white: "#fff",
      off_white: "#F6F6F3",
      light_gray: "#F1F1F1",
    },
    extend: {},
  },
  variants: {},
  plugins: [],
};